POST https://crud-node-a7h4.onrender.com/usuarios
Content-Type: application/json

{
    "nome": "Thales",
    "email": "thspanhol@gmail.com",
    "senha": "Teste01"
}

###

GET https://crud-node-a7h4.onrender.com/usuarios?search=

###

PUT https://crud-node-a7h4.onrender.com/usuarios/1cb67a86-39c9-428f-aba4-08ea988893df
Content-Type: application/json

{
    "nome": "Mika",
    "email": "thspanhol123@gmail.com",
    "senha": "Teste01"
}

###
DELETE https://crud-node-a7h4.onrender.com/usuarios/1cb67a86-39c9-428f-aba4-08ea988893df
